import React from 'react';

interface RankMathSchemaProps {
  schemas?: string[];
}

/**
 * Safely renders Rank Math Schema.org JSON-LD scripts generated by Rank Math in WordPress.
 */
export default function RankMathSchema({ schemas }: RankMathSchemaProps) {
  if (!schemas || schemas.length === 0) return null;

  return (
    <>
      {schemas.map((jsonString, idx) => (
        <script
          key={`rank-math-schema-${idx}`}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonString }}
        />
      ))}
    </>
  );
}
